### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DanielZhang111**

### CODE REVIEW

**Comment by DanielZhang111** [comment]
Can you check? I think i might've copied it wrong, as some information got lost in the process...

**Comment by 0silverback0** [comment]
yea there some missing info

**Comment by DanielZhang111** [comment]
What needs to be changed?

**Comment by DanielZhang111** [comment]
I edited it, now does it have all the missing info?

**Comment by 0silverback0** [comment]
Looks good! Thank you

**Comment by DanielZhang111** [comment]
Did it count for hacktoberfest?

**Comment by DanielZhang111** [comment]
Oh it did, Thank you so much !!! :)

**Comment by 0silverback0** [comment]
Yes of course! Maybe we can collaborate again!

**Comment by DanielZhang111** [comment]
Ok! :)

**Pull request merged**
